### PR TITLE
Silence reactivity warnings in (standard Web APIs) `*Observer` callbacks

### LINKED ISSUE #81: False positive in standard `*Observer` web APIs
**Describe the bug**

I believe callbacks for the `*Observer` category of web APIs should be treated like those for `setTimeout` and friends and not marked as untracked.

**To Reproduce**
```typescript
const [signal] = createSignal(5);

new IntersectionObserver(() => console.log(signal()));
new MutationObserver(() => console.log(signal()));
new PerformanceObserver(() => console.log(signal()));
new ReportingObserver(() => console.log(signal()));
new ResizeObserver(() => console.log(signal()));
```

**Expected behavior**

Using signals in these kinds of callbacks should not generate a warning.

**Screenshots**
Rule "solid/reactivity" gives a warning that reads "This function should be passed to a tracked scope (like createEffect) or an event handler because it contains reactivity." for the code provided above

- [x] I would be willing to contribute a PR to fix this issue

### PR DESCRIPTION
**Pull request by macarie**
This should fix #81.

I don't have much experience building eslint rules, so I don't know if this is the right approach, but it seems to be working and doesn't break any existing tests.

If you don't think these warnings should be silenced, please, feel free to close the PR!

### CODE REVIEW

File: src/rules/reactivity.ts [hunk 1]
```diff
@@ -878,16 +879,24 @@ const rule: TSESLint.RuleModule<MessageIds, []> = {
...
               "setTimeout",
               "setImmediate",
               "requestAnimationFrame",
               "requestIdleCallback",
+              // Observers from Standard Web APIs
+              "IntersectionObserver",
+              "MutationObserver",
+              "PerformanceObserver",
+              "ReportingObserver",
+              "ResizeObserver",
```
Comment (macarie) [inline src/rules/reactivity.ts:893]: These should be all the standard Web APIs that have the same signature and behavior according to [this MDN page](https://developer.mozilla.org/en-US/docs/Web/API).

**Comment by joshwilsonvu** [comment]
Thanks for the contribution! You're absolutely right that these Observer callbacks should be handled by the rule in the same way as timers. I'll go ahead and get this merged shortly. 🎉
